- name: Instalar dependencias del sistema y Docker
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - software-properties-common
      - python3-debian
      - python3-docker
    state: present
    update_cache: yes

- name: Agregar el repositorio oficial de Docker
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: https://download.docker.com/linux/ubuntu
    suites: "{{ ansible_facts['distribution_release'] }}"
    components:
      - stable
    architectures:
      - amd64
    signed_by: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Instalar Docker CE y componentes
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: Asegurar que Docker esté iniciado y habilitado
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
